### ISSUE TITLE
Create Login Widget for Authentication

### ISSUE THREAD

**Issue by ryw** [astronomerio/public-api-houston-explorer-v1#1]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/engineering/issues/390)

@thisisamurray commented on [Thu Aug 10 2017](https://github.com/astronomerio/public-api-houston-explorer/issues/1)

Users should be able to provide a username and password in order to have the resulting token stored within their current session.

Needs:
- [x]  Username and password form fields with validation
- [x] Error reporting on response
- [x] Token storage within local storage, automatically log user in if present
- [x] Logout functionality, clear local storage token
- [x] Style appropriately

---

@ryw commented on [Tue Sep 26 2017](https://github.com/astronomerio/public-api-houston-explorer/issues/1#issuecomment-332379118)

@thisisamurray is this issue done/closable?

---

@thisisamurray commented on [Tue Sep 26 2017](https://github.com/astronomerio/public-api-houston-explorer/issues/1#issuecomment-332380634)

It is still active.

---

@thisisamurray commented on [Tue Sep 26 2017](https://github.com/astronomerio/public-api-houston-explorer/issues/1#issuecomment-332380698)

Will check progress tomorrow and update

---

@thisisamurray commented on [Fri Sep 29 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-333220081)

@ryw Julian is actively working on it and is expecting completion for next week. 

---

@thisisamurray commented on [Fri Sep 29 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-333221354)

BTW this ticket is in regards to houston-explorer.staging.astronomer.io

---

@ryw commented on [Fri Oct 06 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-334841350)

URL is houston-explorer.dev.astronomer.io right? I don't see a login widget...

---

@thisisamurray commented on [Fri Oct 06 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-334847134)

I don't remember closing this ticket out, I'm reopening it

---

@thisisamurray commented on [Fri Oct 06 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-334847339)

@jlaneve how close are you to issue completion?

---

@jlaneve commented on [Sat Oct 07 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-334908976)

This feature is finished but not merged - I'm in the process of creating a new version of Houston Explorer, so I was planning on waiting until that's ready to be deployed. 

---

@ryw commented on [Sun Oct 08 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-335026970)

Why are we building a new version of Houston Explorer?

---

@jlaneve commented on [Tue Oct 10 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-335611146)

We're updating it to optimize the project using a similar tech stack as the app. My goal is to have it done by mid next week.

---

@jlaneve commented on [Mon Oct 23 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-338804990)

Update: the feature has been merged but may still be waiting to be deployed. Further development on the new version of Houston has been put on hold, as I have higher priority tasks. 

---

@thisisamurray commented on [Mon Oct 23 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-338825563)

@jlaneve Which repo? https://github.com/astronomerio/public-api-houston-explorer was pushed to prod last week with your login widget. But none of the style changes you've demo'd before. Please note next steps in this ticket, none of our deployments are automatic, and if it needs to go up then someone needs to do it.

---

@thisisamurray commented on [Thu Nov 02 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-341387543)

@jlaneve Circling back to see what are next steps to get your code deployed.

---

@jlaneve commented on [Thu Nov 02 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-341609562)

Apologies for the lack of communication. This issue is not finished, and it's currently not a priority for me; I received other work with tighter deadlines.

---

@abrongersma commented on [Sat Nov 04 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-341909674)

@gregbrunk can you get this over the finish line?

---

@gregbrunk commented on [Mon Nov 06 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-342328827)

Is this he same as: https://github.com/astronomerio/engineering/issues/378 which is closed? @thisisamurray?

---

@thisisamurray commented on [Mon Nov 06 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-342337095)

@gregbrunk Auth is in https://github.com/astronomerio/public-api-houston-explorer, but Julian created a separate repo (https://github.com/astronomerio/public-api-houston-explorer-v1) that updated a lot of the structure and overhauled the styling. 

We either need to finish the new project (with the styling) and add the most recent docker and auth functionality... or add styling to the older project so it doesn't look like a child made it in 1995. @jlaneve Is the new repo fine for Greg to take over? Or should he just style the current one so we can finally close this ticket. Your comment on Oct. 23rd made it seem like it just needs to be deployed so I assume the new one is close to completion.

---

@gregbrunk commented on [Wed Nov 15 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-344718446)

@jlaneve can you answer @thisisamurray's question above?

---

@ryw commented on [Sun Nov 19 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-345520793)

@jlaneve get w/ @gregbrunk on this ASAP so we can close this out

---

@jlaneve commented on [Mon Nov 20 2017](https://github.com/astronomerio/engineering/issues/390#issuecomment-345889770)

Getting to this next week... It needs a few finishing touches but don't have the capacity to get to it this week.

**Comment by jlaneve** [comment]
Closing with the merge of https://github.com/astronomerio/public-api-houston-explorer/pull/3
